### PR TITLE
Bode margins plot

### PR DESCRIPTION
**Pull request by icam0**
Added display of the phase and gain margins to the bode plots in order to emulate matlab like functionality when calling margin(sys) in matlab. Can be used when calling bode(sys, margins=True). Attached 2 screenshots showing the plots in matplotlib and matlab side by side.

figure_1_matlab
figure_1_python

### CODE REVIEW

**Comment by icam0** [comment]
Build seems to be failing due to issue #194

**Comment by repagh** [comment]
I don't see what the 

`import sys as system `

line is for. Seems not to be used, and renaming it system is not a good idea in this context

**Comment by icam0** [comment]
@repagh , you are right. I suspect this was a leftover from some testing on my part. I removed it.

**Comment by murrayrm** [comment]
Note: this PR has been included in PR #209.  If that PR is merged, can delete this one.

**Pull request merged**
