### PR TITLE
Addressing #84 and #85

### PR DESCRIPTION
**Pull request by mp4096**
* Compute poles of a state-space system using `numpy.linalg.eigvals` as suggested in #84 
* Replaced matrix inversion in the feedback computation by `numpy.linalg.solve` as suggested in #85 
* Also replaced the singularity check with a more stable one. [`numpy.linalg.matrix_rank`](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.linalg.matrix_rank.html) uses a reasonable numerical threshold, so that we don't need to check `abs(det(F))` by hand. Determinant is actually very sensitive to matrix scaling, so better not use it. Both the determinant and the SVD required for `matrix_rank` are cubic, so there should be no slowdown.

### CODE REVIEW

**Comment by mp4096** [comment]
Travis fails exactly at the [same test](https://travis-ci.org/python-control/python-control/builds/114399599) as `master`, also see #70

**Comment by pmli** [comment]
Kudos for finding `abs(det(F))`. Determinant gives no information about the distance to singularity, therefore it cannot be used to numerically check for singularity. SVD is definitely much better. But, wouldn't it be even better to drop the singularity check and trust [`numpy.linalg.solve`](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html) to raise `LinAlgError` if singularity is detected? Do you have a use case when `numpy.linalg.matrix_rank` detects singularity, but `numpy.linalg.solve` doesn't?

**Comment by mp4096** [comment]
Thanks for the hint. Indeed, an additional SVD seems to be superfluous. However, it can be really helpful.

Consider this code:
```python
import numpy as np
import matplotlib.pyplot as plt

matrix_size = 3

for spread in [5, 10, 20]:
    A1 = np.random.rand(matrix_size, matrix_size)
    A2 = np.diag(np.logspace(-spread, +spread, matrix_size))
    A3 = np.random.rand(matrix_size, matrix_size)
       
    A = A1@A2@A3   
       
    invA_A = np.linalg.solve(A, A)
    
    message = "Matrix size: {:d}, matrix rank: {:d}"    
    
    print(message.format(matrix_size, np.linalg.matrix_rank(A)))

    # Should be an identity matrix
    plt.figure()
    plt.imshow(np.log10(np.absolute(invA_A)), interpolation="none")
    plt.colorbar()
```

So instead of raising an exception, `numpy.linalg.solve` just returns some numerical garbage. The problem is, `numpy.linalg.solve` relies on LAPACK's [`DGESV`](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve.html#ga5ee879032a8365897c3ba91e3dc8d512), which in turn calls [`DGETRF`](http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational.html#ga0019443faea08275ca60a734d0593e60) to perform an LUP decomposition. `DGETRF` raises an exception only if a diagonal element is _exactly_ zero:
```
INFO is INTEGER
= 0:  successful exit
< 0:  if INFO = -i, the i-th argument had an illegal value
> 0:  if INFO = i, U(i,i) is exactly zero. The factorization
    has been completed, but the factor U is exactly
    singular, and division by zero will occur if it is used
    to solve a system of equations.
```

Hence, numerical rank loss cannot be detected in `numpy.linalg.solve`

**Comment by pmli** [comment]
Thanks for the detailed explanation. I assumed NumPy/SciPy would emulate Matlab with its warnings about large condition numbers, using [`DGESVX`](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve.html#ga9d90ccf6e340cacd08b7bbbb502ceb21). At least, there is an open [NumPy issue](https://github.com/numpy/numpy/issues/3755) concerning exactly this, although it is quite old. Until it is closed, I don't see a way to cheaply estimate the condition number in NumPy which could replace SVD.

**Comment by mp4096** [comment]
Oh, I didn't knew about this issue, thanks! But it doesn't seem they're going to do anything about this behaviour.

Anyway, most technical systems have very few (in terms of linear algebra :wink:) inputs/outputs. I think this additional SVD-based rank check will makes things slower only if there are at least 1000 inputs/outputs (we're inverting `D` here).

**Comment by mp4096** [comment]
Thank you! I think one can close #84 and #85 now.

**Pull request merged**
