### PR TITLE
Performance improvements to _remove_useless_states routine in statesp.py

### PR DESCRIPTION
**Pull request by adm78**
- avoid looping through states 
- significant performance improvement in the creation of large state space models

### CODE REVIEW

**Comment by adm78** [comment]
Please let me know if you require any modifications to this PR. It would be great to get it merged into the master branch soon.

**Comment by repagh** [comment]
Is np.concatenate correct? You could end up with states that are removed for both reasons. 
Maybe use np.union1d?
It seems to work now, but that relies on np.delete graciously accepting the indexes specified twice.

**Comment by adm78** [comment]
I'm not sure it's possible but I've replaced the np.concatenate with np.union1d just to be safe. 

Looks like some of the tests are failing due to slycot import errors...

**Comment by murrayrm** [comment]
Travis CI tests are fixed in PR #280.  Will merge that into master and then ask pending PRs to merge the change so that we can be sure things are working.

**Pull request merged**
