### PR TITLE
Use slycot's tb05ad for faster and more accurate frequency response e…

### PR DESCRIPTION
**Pull request by rabraker**
This pull request addresses issue [#116](https://github.com/python-control/python-control/issues/116).

It uses the (relatively) newly wrapped [TB05AD](https://github.com/python-control/Slycot/pull/10) function from Slycot, when Slycot is available. If slycot is not available, I instead use the state space built-in method `horner`, rather than converting to a transfer function for the evaluation. 

This passes the unit tests on my machine (python 2.7), but currently it looks like the travis build is [failing](https://travis-ci.org/python-control/python-control/builds/323626585) so I'm not sure what happens with other versions.

### CODE REVIEW

**Comment by murrayrm** [comment]
@rabraker Can you rebase these changes against the current master.  That should fix up the problems in Travis CI and allow testing against python 3.5 and 3.6.

**Comment by rabraker** [comment]
I'm evidently all thumbs with this rebasing business. Whatever I did makes all the checks pass, but somehow there are commits from others going back almost a year in this PR now. I don't know how to fix that.

So it seems easiest to me to delete this PR and I'll just make a new, clean one.

**Comment by murrayrm** [comment]
Pretty sure there is a way to rewrite history that will make this a clean commit.  @slivingston is a master at git, perhaps he has some suggestions?  

One possibility is that you didn't grab the upstream changes from python-control:master and that is causing the large number of extraneous commits.  As I check, I did a manual merge with my copy of the master branch and the only change was to statesp.py.  I think if you do `git pull upstream master` on your branch, it will pull in all of the latest changes and leave you with a clean commit that you can then push back.

**Comment by rabraker** [comment]
With my branch `freqresp_tb05ad` checked out, I tried what you suggest:

```
git pull upstream master
From https://github.com/python-control/python-control
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```
ie, this had no effect. I'll just close this PR and submit another.

**Pull request closed without merging**
