### PR TITLE
Solve #862 and #864: bode_plot phase wrapping incorrect for multiple systems

### PR DESCRIPTION
**Pull request by henklaak**
Function argument clobbered by local assignment. Use local variable instead.

### CODE REVIEW

**Comment by henklaak** [comment]
Need an extra pair of eyes here. Can't relate the errors to the PR work.

**Comment by henklaak** [comment]
matplotlib 3.6.3 => 3.7.* seems to break our tests. Will investigate further.

**Comment by henklaak** [comment]
Solves #862 and #864. If you prefer, I can make separate PRs.

**Comment by murrayrm** [comment]
Thanks for the fixes!

**Pull request merged**
