### PR TITLE
Add pandas to pyproject.toml

### PR DESCRIPTION
**Pull request by KybernetikJo**
Adds pandas to pyproject.toml.

Allows optional install

```bash
pip install control[pandas]
pip install control[pandas,slycot]
...
```

### CODE REVIEW

**Comment by bnavigator** [comment]
I don't really see a big enough benefit of adding a single optional **well known** package with the same name as the package.

What's the effective difference between `pip install control pandas` and `pip install 'control[pandas]'`?

**Comment by bnavigator** [comment]
FTR, I am guilty of starting that kind of extra with Slycot in #678. Probably would not do it again.

**Comment by KybernetikJo** [comment]
> I don't really see a big enough benefit of adding a single optional **well known** package with the same name as the package.
> 
> What's the effective difference between `pip install control pandas` and `pip install 'control[pandas]'`?

These are valid points, so I looked for other projects that use the pattern. I was able to find two well known packages:
- polars https://github.com/pola-rs/polars/blob/main/py-polars/pyproject.toml
- cvxpy https://github.com/cvxpy/cvxpy/blob/master/pyproject.toml

The reason could be
- to document all dependencies (also optional) in pyproject.toml
- to indicate that single options are valid installations `pip install control[pandas]` 
- to ensure the right version of optional packages
  - `pip install control[slycot]` is actually `pip install "slycot>=0.4.0" control`
  - `pip install control[pandas]` would be `pip install "pandas>=1.5.0" control`
  
 
Remark:
Well, the benefits don't seem to be big enough. I will keep the PR open for a few weeks, and then I will close it.

**Comment by KybernetikJo** [comment]
Well, the benefits were not big enough.

**Pull request closed without merging**
