### PR TITLE
Add IPython Notebook

### PR DESCRIPTION
**Pull request by djvita**
Hello python-control! I forked and pip installed this library to do some
model analysis. As a form of thanks, I've converted your example
[Vertical takeoff and landing aircraft](http://www.cds.caltech.edu/~murray/wiki/index.php/Python-control/Example:_Vertical_takeoff_and_landing_aircraft) into a notebook, with some
improvements from the page. Take a look! 
Regards, Vita

### CODE REVIEW

**Comment by slivingston** [comment]
Awesome! The file should be named something indicative of the example, e.g., `pvtol-lqr-nested.ipynb`.

For whoever will review this PR, the notebook can be [rendered directly from GitHub.com](https://github.com/blog/1995-github-jupyter-notebooks-3).

**Comment by djvita** [comment]
Thanks! happy to help out.

**Comment by cwrowley** [comment]
This looks really nice--thanks @djvita!  I reopened this pull request so we can merge it in.  Could you rename the file as @slivingston suggested and push the change to your fork?

**Comment by slivingston** [comment]
The page linked to in the OP is no longer active. For posterity, an archived copy is http://web.archive.org/web/20150217170735/http://www.cds.caltech.edu/~murray/wiki/index.php/Python-control/Example:_Vertical_takeoff_and_landing_aircraft

**Comment by slivingston** [comment]
@djvita Could you change the file name? Ideally you would do so by rebasing, thus replacing the single commit of your original pull request, because there is no reason to keep the original file name in commit history.

**Comment by murrayrm** [comment]
Merged with new filename.

**Pull request merged**
