### PR TITLE
changes to rlocus to be compatible with discrete-time systems

### PR DESCRIPTION
**Pull request by sawyerbfuller**
* give correct z-plane damping ratio on mouse click 
* auto zoom into unit circle
* show zgrid with lines of constant damping ratio and natural frequency if desired
* sisotool now plots dots instead of a continuous line for discrete-time systems 
* fixed spelling of variables in a couple of places

### CODE REVIEW

**Comment by murrayrm** [comment]
Fixed up a few conflicts with changes to `rootlocus.py` from PR #413.  Will merge if Travis CI passes.

**Comment by murrayrm** [comment]
Screwed up.  The merge with PR #413 is a bit more complicated.  Will handle later.

@sawyerbfuller My plan is to back out my latest commit and then rebase on top of current master (which will get PR #413).  If you have suggestions for any conflicts that might come up, let me know.

**Comment by murrayrm** [comment]
Fixed up the conflicts.  If Travis CI succeeds, this should be ready to merge.

@sawyerbfuller Probably worth a quick look to make sure I didn't screw anything up.

**Comment by sawyerbfuller** [comment]
Sorry about the merge problems. I’m not enough of a git guru yet to figure out how to do a test merge at home. Will check for any issues next time I’m at a computer.

**Comment by murrayrm** [comment]
Thanks @sawyerbfuller.  I think I got all of the changes got mapped over correctly, so it should just take a quick look to make sure I didn't miss anything (unit tests are OK).

**Comment by sawyerbfuller** [comment]
Ok I took a quick look through. Couldn't figure out how to see exactly what changes you had to make, but I checked through my local diffs and everything there seems to be in this branch. So if it passes unit tests, seems like all must be good.

**Pull request merged**
