### PR TITLE
Enable doctest

### PR DESCRIPTION
**Pull request by henklaak**
WIP to see if we can get a doctest clean build.

### CODE REVIEW

**Comment by bnavigator** [comment]
The docs are not really written so that doctests would pass without errors. You're welcome to fix them up. Best turnaround for that is to run the tests in your local development environment.

**Comment by henklaak** [comment]
Yes, I run them locally now. I just wasn't sure if the GitHub machinery would work, package dependencies and so on.

**Comment by henklaak** [comment]
I'm writing this PR in anticipation of me adding lots more examples. I'm fairly new to python-control, so I hope I'll identify the pain points and document them along the way.

**Comment by henklaak** [comment]
Retracting. Will clean up and redo soon.

**Pull request closed without merging**
