### PR TITLE
Fix python2 print in examples

### PR DESCRIPTION
**Pull request by don4get**
This one is to answer to issue https://github.com/python-control/python-control/issues/208, concerning the `python2 print style`.

I realized the example testing the import of slycot was not working and I fixed it.

### CODE REVIEW

**Comment by murrayrm** [comment]
@don4get Can you rebase this against the current master?  There were some changes in some of the pending PRs that conflicted.  Thanks.

**Comment by roryyorke** [comment]
Sorry, I should have noted that #263 fixes #208, at least w.r.t. Python-2 style print.

**Comment by don4get** [comment]
@roryyorke Well done ;) 
I rebased and cleaned my branch -> new purpose, minor: clean two examples.

**Comment by don4get** [comment]
Since I renamed the branch, I had to create another PR: https://github.com/python-control/python-control/pull/267

**Pull request closed without merging**
