### PR TITLE
UnSkipTest: these tests pass on Python 2.7, 3.3, 3.4, and 3.5.

### PR DESCRIPTION
**Pull request by roryyorke**

### CODE REVIEW

**Comment by slivingston** [comment]
Does anyone know why these were being skipped originally? The `unittest.skip` decorators were introduced in 6d9da6eacd81887589fdfae25f3076353a013690, which was a big commit that mixes many different kinds of changes, and the commit message does not offer relevant explanation.

**Comment by slivingston** [comment]
Otherwise, I agree with the changes and will merge after some comment about the original motivation is made.

Perhaps @jgoppert knows.

**Comment by murrayrm** [comment]
I took a quick look and couldn't see any reason why these were skipped.

**Comment by slivingston** [comment]
Before merging this, I found that all tests pass on a Debian GNU/Linux x86_64 box with Python versions 2.7.9, 3.3.6, 3.4.2, 3.5.2

**Comment by murrayrm** [comment]
Decided not to track this against milestone 0.8.0 since it is primarily an internal change (so not visible to users).

**Pull request merged**
