### PR TITLE
Arrow head length and head width option is added in nyquist_plot function

### PR DESCRIPTION
**Pull request by geekonloose**

### CODE REVIEW

**Comment by murrayrm** [comment]
It looks like the line style or something changed so that *every* line in the is marked as deleted then added.

Can you try to reset the line style back to the original so that we can see only those lines that changed?  Much easier to track updates that way.

**Comment by geekonloose** [comment]
My editor was automatically formatting to pep8 format sorry for that. I have reformatted file as possible. Now it should read alright.

**Comment by murrayrm** [comment]
Can you just go back to the original file and only edit the lines that actually need to be changed?  Just putting the lines changed in the PR comments won't let people see what actually changed if they do `git diff`.

**Comment by murrayrm** [comment]
Looks like 8f8565b3b7d58544972ea2556fa6261ee1b31dc1 fixed the problem but then 1f4885d changed it back?

**Comment by murrayrm** [comment]
Also: I suggest using keywords that are more descriptive than `hw` and `hl`.  How about `arrowhead_width` and `arrowhead_length`?

**Comment by geekonloose** [comment]
ok I will do that.

**Pull request merged**
