### PR TITLE
Improve `acker` pole placement doc

### PR DESCRIPTION
**Pull request by pierre-haessig**
Hello,

This is a follow-up of #1004, still on pole placement, but now turning to [`acker` docstring](https://python-control.readthedocs.io/en/0.10.0/generated/control.acker.html#control.acker).

As a first step, this adds a "See Also" section to `place` and `place varga`.

However, I have two more ideas to extend this PR:
- add reference to the Ackermann's formula. I've found § 2.3.5 in the "Linear Control Theory" book by F. W. Fairman, 1998, but I'm not sure it matches perfectly with what's implemented.
- to the best of my (quite limited) knownledge, Ackermann's formula is for *single input* systems (and I got some linear algebra error on a test with a system with 2 inputs). If correct, I suggest to add a `ValueError` if `B.shape[1] > 1`.

### CODE REVIEW

**Comment by pierre-haessig** [comment]
Oups, I didn't see PR #1007 and pushed my own commit to fix `place_varga` doctring. Now I have to fix the conflict!

**Comment by pierre-haessig** [comment]
> Now I have to fix the conflict!

Done!

**Comment by slivingston** [comment]
@pierre-haessig Thanks! I am going to squash-merge this because the [second commit](https://github.com/python-control/python-control/pull/1006/commits/4f0e9b7142b605979e84ef093fc3afdddbd3287d) is not used after you resolved the conflict.

**Comment by slivingston** [comment]
Regarding the other two items in your opening post:
1. For widely known results like Ackermann's formula, I recommend to use an open access reference, if available. The book [Feedback Systems](https://fbswiki.org/wiki/index.php/Feedback_Systems:_An_Introduction_for_Scientists_and_Engineers) can be used for this. Ackermann's formula is given in equation (7.21) in Chapter 7.
2. Ackermann's formula is only for single-input systems. This aligns with the similar [acker function in Matlab](http://www.ece.northwestern.edu/local-apps/matlabhelp/toolbox/control/ref/acker.html). The function always raises an exception if the system has more than 1 input, but the error message may be confusing. We could add a check with `ValueError` as you suggest, or the documentation can add a note about single-input systems (or both). Feel free to create another pull request with it.

As an aside, I was not able to find a description of `acker` in the [official Matlab documentation](https://www.mathworks.com/help/control/referencelist.html). Perhaps they removed it?

**Comment by pierre-haessig** [comment]
> As an aside, I was not able to find a description of `acker` in the [official Matlab documentation](https://www.mathworks.com/help/control/referencelist.html). Perhaps they removed it?

Neither did I. I only found an online copy of a unspecified Matlab version here: www.ece.northwestern.edu/local-apps/matlabhelp/toolbox/control/ref/acker.html (in the source code, the date 2002 is mentioned). I don't know when it was removed.

**Pull request merged**
