### PR TITLE
Configure flake8. Fix flake8 errors where possible.

### PR DESCRIPTION
**Pull request by jgspiro**
Fixed most flake8 warnings and errors in control package.  Used autopep8 tool to fix most whitespace related errors. Test files are not done at the moment.

Some other fixed issues : 

- missing import for `warn()` statement
- fixed some documentation (missing parameter docstring, ...)

Currently ignored flake8 warnings are :  E402 (import not at top of file) and W605 (invalid escape sequence)

When reviewing the pull request, **hiding whitespace changes** will make it a lot easier to review all changes.

### CODE REVIEW

**Comment by jgspiro** [comment]
As planned, the Travis checks are failing, because I added a flake8 run to the travis configuration.
These are the errors/warings that are left, where it would be good to have some input about what to do with them : 

```control/mateqn.py:876:9: F841 local variable 'E_b' is assigned to but never used
control/lti.py:173:30: E721 do not compare types, use 'isinstance()'
control/modelsimp.py:413:5: F841 local variable 'Ymat' is assigned to but never used
control/frdata.py:371:13: E722 do not use bare 'except'
control/frdata.py:480:5: E722 do not use bare 'except'
control/freqplot.py:601:9: E722 do not use bare 'except'```

**Comment by moorepants** [comment]
control/lti.py:173:30: E721 do not compare types, use 'isinstance()'

Using `isintance(thing, str)` is fine for type checking. The `if type(thing) == str` above these lines is not a good idiom.

https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python

control/modelsimp.py:413:5: F841 local variable 'Ymat' is assigned to but never used

Remove it.

control/frdata.py:371:13: E722 do not use bare 'except'
control/frdata.py:480:5: E722 do not use bare 'except'
control/freqplot.py:601:9: E722 do not use bare 'except

Add specific exceptions.

**Comment by moorepants** [comment]
You also did not follow my suggestion to submit 1 PR per py file (or per sub-package at max).

**Comment by jgspiro** [comment]
> You also did not follow my suggestion to submit 1 PR per py file (or per sub-package at max).

Since there is only 1 subpackage, I followed that suggestion.  I didn't think fixing 25+ individual files and creating pull requests for all of them would be easier to manage.   The person reviewing could always review one file at a time.

**Comment by jgspiro** [comment]
> control/lti.py:173:30: E721 do not compare types, use 'isinstance()'
> 
> Using `isintance(thing, str)` is fine for type checking. The `if type(thing) == str` above these lines is not a good idiom.
> 
> https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python
> 
> control/modelsimp.py:413:5: F841 local variable 'Ymat' is assigned to but never used
> 
> Remove it.
> 
> control/frdata.py:371:13: E722 do not use bare 'except'
> control/frdata.py:480:5: E722 do not use bare 'except'
> control/freqplot.py:601:9: E722 do not use bare 'except
> 
> Add specific exceptions.

Right. I understand what the errors mean. The point was to get suggestions by someone who wrote the code (or, has more commits, or wants to review) before I change it to something else.

**Comment by moorepants** [comment]
I offered my time and suggestions and you clearly don't respect that from your response. I have nothing more to offer.

**Comment by repagh** [comment]
Would it be better to just configure & run flake8 with the --exit-zero flag? Then the checks won't fail due to flake8, and we can slowly, unit-by-unit, fix the formatting and code. 

I don't feel happy either with over 30 changed files in one PR and I would not like this to get hurried through.

**Comment by ilayn** [comment]
This has to be done in a separate Travis CI job to make sure that later no new PEP8 problems creep in. Over SciPy, we created a very fast job that runs `pycodestyle` and `pyflakes` that checks specifically this and a few other cosmetics. Then you just need to see the green checkmark and not review everything.

**Pull request closed without merging**
