### PR TITLE
Added option for computing anti-stabilizing solutions of Riccati equations

### PR DESCRIPTION
**Pull request by dbacc**
Sometimes also anti-stabilizing solutions of Riccati equations are of interest. The slicot routine offers to compute these solutions, so I added an option in the `care` and `dare` routine, which both default back to the stabilizing case.

### CODE REVIEW

**Comment by moorepants** [comment]
Can you please add unit tests to demonstrate the new functionality?

**Comment by dbacc** [comment]
Sure, done ;)

**Comment by murrayrm** [comment]
Thanks for your contribution!  The unit test needs to go in `control/tests` and use the `unittest` framework.  I suggest adding this to `statefbk-test.py` since that is where other unit tests associated with controller synthesis currently live.

**Comment by dbacc** [comment]
_now_ it should be at the correct location ;)

btw. Why is @coveralls telling that coverage decreased?

**Comment by murrayrm** [comment]
@dbacc Can you merge changes from latest master to get Travis CI working again (see PR #280 for more info).  Thanks.

**Comment by murrayrm** [comment]
Changes look good.  Will include in 0.8.2 release after verifying there are no conflicts.

**Pull request merged**
