### PR TITLE
Feature: allow differing numerator and denominator degree in Pade app…

### PR DESCRIPTION
**Pull request by roryyorke**
Intended to be simple-as-possible implementation (or at least, as-close-to-previous-as-possible).

I've added tests - couldn't find any existing ones.

### CODE REVIEW

**Comment by slivingston** [comment]
@jason-s or anyone, Is there a DOI or more complete reference for the paper by Vajta? The URL in #73 is directly to the author's website, and my brief search did not yield results.

**Comment by jason-s** [comment]
@slivingston I am not sure there is another online source; everyone citing Vajta seems to refer to the author's website.

**Comment by jason-s** [comment]
Well, you could cite ResearchGate's copy: https://www.researchgate.net/publication/229003251_Some_remarks_on_Pade-approximations

**Comment by jason-s** [comment]
Other references are:

Moler, Cleve, and Charles Van Loan. "Nineteen dubious ways to compute the exponential of a matrix, twenty-five years later." SIAM review 45.1 (2003): 3-49. http://www.cs.cornell.edu/cv/researchpdf/19ways+.pdf or the original (1978) at http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.129.9283

Hanta, V., and A. Procházka. "Rational approximation of time delay." Institute of Chemical Technology in Prague. Department of computing and control engineering. Technická 5.166 (2009): 28. http://www2.humusoft.cz/www/papers/tcp09/035_hanta.pdf

**Comment by slivingston** [comment]
@roryyorke The proposed changes and additions are good. In delay_test.py, you write "...ideally test to numerical limits". Could you comment how that may be achieved as future work?

Thanks, @jason-s. I will add the references to the docstring of pade() after merging.

**Comment by roryyorke** [comment]
@slivingston there are two possible extremes I can think of: large order (according to @jason-s 's article [1], maximum is n=21), and very large and small T (obviously with order 20 and T=1e16 result is going to overflow - not sure if there are numerical issues for more realistic but still large T).  

I think this PR closes #73 ?

[1] http://www.embeddedrelated.com/showarticle/927.php

**Pull request merged**
