### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by cwrowley**
There were some problems with the way the sphinx documentation was configured, in particular the path setting in `doc/conf.py`.  The changes in this pull request fix this, and create "mocks" for numpy and scipy routines so that these packages do not need to be installed for the documentation to build (necessary on readthedocs.org, and a good thing in general).

This branch is based on the 0.6d release, and builds successfully on readthedocs.org (but not on travis.ci, because this release predates that setup).  My plan is to merge this in to master, and then improve the documentation further.

### CODE REVIEW

**Comment by cwrowley** [comment]
Finally getting back to this.  I suggest we no longer support Python 3.2, and instead support 3.3 and 3.4 (and 2.7, and possibly 2.6).  That's what Anaconda supports now, and that is probably the main distribution people will be using.  (It's certainly what I suggest to people.)  This has the added benefit of being able to use the conda installer for Travis builds, which is much faster and cleaner than installing everything from source like we do now.

**Comment by slivingston** [comment]
I support the recommendation to not support Python 3.2. Trying to support v3.2 in addition to the other versions of Python listed in [the comment above](https://github.com/python-control/python-control/pull/41#issuecomment-83588705) causes complications with respect to denoting Unicode strings (cf. [PEP 414](https://www.python.org/dev/peps/pep-0414/)).

@cwrowley, I can review and merge this pull request when you are ready. I understand this to be a pull request that addresses issue #33.

**Comment by cwrowley** [comment]
@slivingston, thanks--this is ready to go as far as I am concerned.  Yes, this addresses issue #33 and #29.

**Comment by murrayrm** [comment]
I merged the lsim improvements from crowley/lsim.  This pull request should be ready for merging into master.  Just waiting on Travis CI to build and complete its checks.

**Comment by murrayrm** [comment]
Errors from Travis CI.  @cwrowley, can you take a look?

**Comment by slivingston** [comment]
Note that the build failure may be spurious. GitHub has been under a big DDoS attack. https://status.github.com

**Comment by slivingston** [comment]
I restarted [the build](https://travis-ci.org/python-control/python-control/builds/56316096), and it succeeded.

**Pull request merged**
