### PR TITLE
Add _repr_latex_ for Jupyter notebooks

### PR DESCRIPTION
**Pull request by alchemyst**
This allows better representation inside the browser:

image

### CODE REVIEW

**Comment by murrayrm** [comment]
Change looks fine, but getting a Travis CI error.

It would be nice to put in this type of functionality for the other LTI subtypes (StateSpace, FRD, etc).  Any chance you have the time and inclination to do that as well?

**Comment by alchemyst** [comment]
I'd be happy to take a run at it, but perhaps we could start by opening issues for the others? I'd specifically like to know what format you'd prefer for the state space.

**Comment by murrayrm** [comment]
@alchemyst Can you merge changes from latest master to get Travis CI working again (see PR #280 for more info).  Thanks.

**Comment by alchemyst** [comment]
@murrayrm ✅

**Comment by repagh** [comment]
Nice, looks good. 
Would it be worthwhile to build the outstr as a list, and at the end return the string with
`''.join(outstr)`
I expect that to be faster.

**Comment by alchemyst** [comment]
@repagh Done. 

My initial implementation was a copy-paste of the current `__str__`. Perhaps we should add an issue for someone to make the same changes there?

**Comment by repagh** [comment]
@murrayrm I think this looks OK to merge

**Pull request merged**
