### PR TITLE
TransferFunction _common_den rewrite - issue #194

### PR DESCRIPTION
**Pull request by repagh**
On my machines I got a consistent issue #194 error. (Mac OSX and Linux). 

After playing around with the seed in convert_test.py, I got slightly different results for the tests. I inspected _common_den (xferfcn.py) with the debugger, and found that in some cases a lot of cancelling poles would be added; the sorting for pole comparison did not consistently work. 

I then re-thought and re-worked the _common_den function, instead of sorting, cycling through all known poles, comparing to poles in the current denominator, marking which ones are found -- to prevent accepting double poles, and remembering which ones are not found.

The whole thing is a lot shorter, and I believe also a lot more robust. I hope this eliminates the elusive #194

### CODE REVIEW

**Comment by repagh** [comment]
I average coverage actually decreased, simply because I made xferfcn.py 58 lines shorter and that file had a coverage wel above average.

**Comment by repagh** [comment]
Please do not merge yet. I now realise that only poles common to an *input* can be removed from the tf's, (thanks to issue #111). I will try to resolve that over the next week or so.

**Comment by murrayrm** [comment]
@repagh It would be great to add a unit test that catches issue #111 while you are at it.

**Comment by repagh** [comment]
I think I got it this time. 
- The convert_test.py smoothly runs
- test case for #111 also works
- I modified/corrected a test case in xferfcn_test.py, same issue, deleted poles

Note that this relies on my fixes to Slycot; these fix a number of edge cases

**Comment by murrayrm** [comment]
I fixed up the Travis CI issues in PR #210 and tested this code (locally) to make sure that it passes unit tests.  On MacOS 10.13 I get the following error:
```
ERROR: testModred (control.tests.matlab_test.TestMatlab)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/murray/Dropbox/macosx/src/python-control/murrayrm/control/tests/matlab_test.py", line 400, in testModred
    modred(self.siso_ss3, [1], 'matchdc')
  File "/Users/murray/Dropbox/macosx/src/python-control/murrayrm/control/modelsimp.py", line 181, in modred
    raise ValueError("Matrix A22 is singular to working precision.")
ValueError: Matrix A22 is singular to working precision.
```
I haven't figured out what specifically in this PR is causing the problem, but need to chase this down before we can merge.

@repagh Can you run this against the latest version of `slycot` and see if you get the same error?

**Comment by repagh** [comment]
I get the same error. 

However, I do not think this should be an issue. The modred is performed on a state-space system created with tf2ss, through slycot. One of the states is removed in modred, and since the tf2ss has been changed, a different set (of equally valid) states has come out of that step. Without control over what  states are chosen for a state-space system, one should not try to eliminate a specific single state. 

Using siso_ss1 instead of self.siso_ss3 for the test works.

**Comment by repagh** [comment]
I also see a bunch of other tests failing (e.g. test_robust). I don't get that same behaviour locally.

**Comment by murrayrm** [comment]
The other tests are failing due to changes that are addressed in PR #210.  I'll test locally and if everything is working then I'll merge PR #210 and then this PR, which should get us back to a working master branch.

**Comment by murrayrm** [comment]
Confirmed that latest change (to `modred` unit tests) fixes the issue on my local machine.  PR #210 is now merged, so this PR is ready to go.

**Pull request merged**
