### PR TITLE
Do not overwrite np = numpy with an array size.

### PR DESCRIPTION
**Pull request by ochurlaud**
The function failed to be called with python3

### CODE REVIEW

**Comment by slivingston** [comment]
I would not expect this to only affect Python 3.

**Comment by slivingston** [comment]
Can you provide an example that demonstrates the error?

Since `np` as an identifier for `numpy` is not used within the function scope after where `np` is assigned to an array size, it is not an error. I agree that changing the name would improve the style, but it is not a matter of correctness.

**Comment by ochurlaud** [comment]
Hum, I don't remember: it was some time ago. Comparing to other modules, t should be call _np I think instead of what I wrote. Anyway: as it's a small fix, without huge repercussions, I think it should be somehow done. 

Even if you don't use my PR, just do the correction somehow?

**Comment by roryyorke** [comment]
I fixed this on #100.  It *is* a bug; if, on that branch, I revert from np_ to np,  I get the error below.  I'd have to read up on how Python handles globals and locals to explain this (did that change in Python 3?).

```
Test h2syn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "robust_test.py", line 34, in testH2syn
    k = control.robust.h2syn(p, 1, 1)
  File "/home/rory/src/python-control/control/robust.py", line 91, in h2syn
    n = np.size(P.A,0)
UnboundLocalError: local variable 'np' referenced before assignment
```

**Comment by ochurlaud** [comment]
Ok, then maybe merging #100 would be better than mine.

**Comment by slivingston** [comment]
Changes from pull request #100 were merged, which subsumes changes from here, [as noted above](https://github.com/python-control/python-control/pull/98#issuecomment-238972383). In particular, cf. lines [93](https://github.com/python-control/python-control/blob/d4e015598cc88d0b08104754b899e1f6156eb68a/control/robust.py#L93) and [157 of control/robust.py](https://github.com/python-control/python-control/blob/d4e015598cc88d0b08104754b899e1f6156eb68a/control/robust.py#L157) as of commit d4e015598cc88d0b08104754b899e1f6156eb68a (current tip of `master` branch).

@ochurlaud Nonetheless, thanks for this pull request. I should have been faster to review it.

**Pull request closed without merging**
